### ISSUE TITLE
App crashes when no fields filled after screen rotation in Attendee details.

### ISSUE THREAD

**Issue by shiv07tiwari** [fossasia/open-event-android#1005]
**Describe the bug**
Generally when no data is entered in Attendee details, it shows a snackbar to enter details.
But when screen is rotated, then instead of snackbar, the app crashes.

**To Reproduce**
Open any event -> Go to Tickets -> Register -> Enter details.
Dont fill anything, rotate the screen. Click on Register.

**Expected behavior**
It should show a snackbar to enter details.

**Screenshots**
![videotogif_2019 02 02_17 26 21](https://user-images.githubusercontent.com/38163725/52163968-3db8ec00-2710-11e9-9896-2ccbecc0261f.gif)

**Logs**

02-02 17:31:27.816 6646-6646/com.eventyay.attendee E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 6646
    java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
        at java.util.ArrayList.get(ArrayList.java:439)
        at org.fossasia.openevent.general.attendees.AttendeeFragment$onCreateView$19.onClick(AttendeeFragment.kt:387)
        at android.view.View.performClick(View.java:6304)
        at android.view.View$PerformClick.run(View.java:24803)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6600)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)

**Smartphone Info:**
Redmi Note5 pro, Oreo 8.1

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by pranavpandey1998official** [comment]
will be solved by #967

**Comment by angmas1** [comment]
unable to reproduce
