### ISSUE TITLE
App is crashing in map fragment.

### ISSUE THREAD

**Issue by chiragw15** [fossasia/open-event-android#1302]
**Actual Behaviour**

App is crashing while running map fragment when mobile data is turned on.

**Expected Behaviour**

It shoudld not crash.

**Steps to reproduce it**
1.) Uninstall the app and run it from android studio.
2.) Switch off the wifi and turn mobile data on. 
3.) Start the app and go to map fragment. The app will crash.
 
**LogCat for the issue**
```
FATAL EXCEPTION: main
Process: org.fossasia.openevent, PID: 5923
java.lang.NullPointerException: Attempt to invoke virtual method 'float org.fossasia.openevent.data.Event.getLatitude()' on a null object reference
  at org.fossasia.openevent.fragments.OSMapFragment.populateMap(OSMapFragment.java:113)
  at org.fossasia.openevent.fragments.OSMapFragment.onViewCreated(OSMapFragment.java:184)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1315)
  at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323)
  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136)
  at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998)
  at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:709)
  at android.os.Handler.handleCallback(Handler.java:746)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5443)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```
**Would you like to work on the issue?**

yes

**Comment by the-dagger** [comment]
Not sure if I am able to reproduce this issue!
