### ISSUE TITLE
Bug :  On clicking schedule  app crashes

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-android#1311]
**Actual Behaviour**

On clicking schedule from naigation drawer app crashes because adapter.notifyDataSetChanged() is called before adapter is initialized.

**Expected Behaviour**

It shouldn't crash.

**LogCat for the issue**

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged()' on a null object reference
                                                                            at org.fossasia.openevent.fragments.DayScheduleFragment$4.accept(DayScheduleFragment.java:153)
                                                                            at org.fossasia.openevent.fragments.DayScheduleFragment$4.accept(DayScheduleFragment.java:147)
                                                                            at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:59)
                                                                            at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200) 
                                                                            at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252) 
                                                                            at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109) `

**Would you like to work on the issue?**

yes

**Comment by Shailesh351** [comment]
Sorry fixed in #1309
