### ISSUE TITLE
App crashing due to IllegalArgumentException 

### ISSUE THREAD

**Issue by addiegupta** [fossasia/open-event-android#1383]
**Describe the bug**

The app is crashing on selecting Search from navigation bar

**To Reproduce**

The app should not crash 

**Logs**

FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 14541
    java.lang.IllegalArgumentException: Required argument "@string/saved_date" is missing and does not have an android:defaultValue
        at org.fossasia.openevent.general.search.SearchFragmentArgs.fromBundle(SearchFragmentArgs.java:34)
        at org.fossasia.openevent.general.search.SearchFragment$safeArgs$2.invoke(SearchFragment.kt:30)
        at org.fossasia.openevent.general.search.SearchFragment$safeArgs$2.invoke(SearchFragment.kt:24)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.fossasia.openevent.general.search.SearchFragment.getSafeArgs(Unknown Source:7)
        at org.fossasia.openevent.general.search.SearchFragment.onCreateView(SearchFragment.kt:59)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2539)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:875)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2084)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1858)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1814)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1715)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:143)
        at android.os.Handler.handleCallback(Handler.java:874)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Screenshots**

![Issue 1383](https://user-images.githubusercontent.com/22665789/54864911-bab52900-4d83-11e9-9d39-2adfc8b71566.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nokia 6.1 Plus|
|Android Version|Pie 9.0  |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by addiegupta** [comment]
This issue might just be some sort of a build error as I am unable to reproduce this now. Can anyone let me know if this is reproducible so I can close this?

**Comment by ShridharGoel** [comment]
Yes, it's reproducible.

**Comment by addiegupta** [comment]
> Yes, it's reproducible.

Thanks for letting me know. Ill start working on it
