### ISSUE TITLE
App getting crashed

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-android#1402]
**Actual Behaviour**

After merging the PR #1371, the app is getting crashed on clicking speakers from navigation drawer.

**Expected Behaviour**

App should not crash.

**Steps to reproduce it**

Take the pull of the latest code. Run the app and click on the speakers in navigation drawer, the app will get crashed.

**LogCat for the issue**

Caused by: android.database.sqlite.SQLiteException: no such column: thumbnail (code 1): , while compiling: SELECT id, name, photo, thumbnail, shortBiography, email, web, facebook, twitter, github, linkedin, organisation, position, country FROM speakers ORDER BY name ASC
                                                                          at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                          at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                                                                          at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                                                                          at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                          at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                          at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                          at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                          at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                                          at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
                                                                          at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
                                                                          at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1202)
                                                                          at org.fossasia.openevent.dbutils.DatabaseOperations.getSpeakerList(DatabaseOperations.java:186)
                                                                          at org.fossasia.openevent.dbutils.DbSingleton.getSpeakerList(DbSingleton.java:119)
                                                                          at org.fossasia.openevent.dbutils.DbSingleton$4.call(DbSingleton.java:126)
                                                                          at org.fossasia.openevent.dbutils.DbSingleton$4.call(DbSingleton.java:123)
                                                                          at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
                                                                          at io.reactivex.Observable.subscribe(Observable.java:10700)
                                                                          at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)

**Screenshots of the issue**

![screenshot from 2017-04-11 23 53 39](https://cloud.githubusercontent.com/assets/12701036/24924573/df43964a-1f12-11e7-9d42-d30ce4551dab.png)

**Would you like to work on the issue?**

Yes, sending the PR resolving the issue.

**Comment by the-dagger** [comment]
Tried running the app, it works fine for me.
Probably @iamareebjamal forgot to update the db version after making changes in the contract.
Clean install should fix it.

**Comment by the-dagger** [comment]
Though the app is crashing on clicking OSM fragment, you might want to take a look at that

**Comment by iamareebjamal** [comment]
I opened similar issue back when short biography was added in database. Database version remains constant over the time schema changes. I didn't change the version following the convention from old commits. Simple workaround is to clear the data. 

If required, it would be better to increment db version for each schema change as suggested by me earlier
