### ISSUE TITLE
App crash on selecting search from bottom nav bar

### ISSUE THREAD

**Issue by angmas1** [fossasia/open-event-android#1406]
**Describe the bug**

App crashes when seleccting search from bottom nav bar

**To Reproduce**

1. Open app
2. Tap on search

**Expected behavior**

App shouldn't crash

**Logs**

2019-03-24 23:36:00.468 31597-31597/com.eventyay.attendee E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 31597
    java.lang.IllegalArgumentException: Required argument "@string/saved_date" is missing and does not have an android:defaultValue
        at org.fossasia.openevent.general.search.SearchFragmentArgs.fromBundle(SearchFragmentArgs.java:34)
        at org.fossasia.openevent.general.search.SearchFragment$safeArgs$2.invoke(SearchFragment.kt:30)
        at org.fossasia.openevent.general.search.SearchFragment$safeArgs$2.invoke(SearchFragment.kt:24)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.fossasia.openevent.general.search.SearchFragment.getSafeArgs(Unknown Source:25)
        at org.fossasia.openevent.general.search.SearchFragment.onCreateView(SearchFragment.kt:59)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2539)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:875)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2084)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1858)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1814)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1715)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:143)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by anhanh11001** [comment]
I think it is already resolved in the latest commits, please try rebasing your development branch

**Comment by angmas1** [comment]
Okay, fixed now closing.
