### ISSUE TITLE
App crash on signup fragment , when Username or password are empty

### ISSUE THREAD

**Issue by theLimitBreaker** [fossasia/open-event-android#1454]
**Describe the bug**
App crash when username or password are empty in signup fragment

**To Reproduce**

1. Go to 'Sign up fragment'
2. Click on 'Last name'
3. without entering anything, Click on `tick`(IME action) on keyboard
4. App crashes

**Expected behavior**
tick button shouldn't try to signup when fields are empty

**Logs**
 ```
Process: com.eventyay.attendee, PID: 19925
    java.lang.IllegalArgumentException: Username or password cannot be empty
        at org.fossasia.openevent.general.auth.AuthService.signUp(AuthService.kt:30)
        at org.fossasia.openevent.general.auth.SignUpViewModel.signUp(SignUpViewModel.kt:43)
        at org.fossasia.openevent.general.auth.SignUpFragment$onCreateView$2.onClick(SignUpFragment.kt:80)
        at android.view.View.performClick(View.java:6608)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:840)
        at org.fossasia.openevent.general.auth.SignUpFragment$onCreateView$1.onEditorAction(SignUpFragment.kt:66)
        at android.widget.TextView.onEditorAction(TextView.java:6280)
        at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:360)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
        at android.os.Handler.dispatchMessage(Handler.java:114)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6716)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Smartphone Info:**

Device : Nokia 6.1         
Android Version : Android 9.0 pie

**Would you like to work on the issue?**

- [ :heavy_check_mark: : ] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
Please take this up on priority

**Comment by codedsun** [comment]
@theLimitBreaker Are you working on this issue?

**Comment by theLimitBreaker** [comment]
Yes ! Currently Working
