### ISSUE TITLE
App crash on selecting an event after navigating from other fragments

### ISSUE THREAD

**Issue by addiegupta** [fossasia/open-event-android#1475]
**Describe the bug**

The app is crashing after navigating to the `EventsFragment` from other fragment and then selecting an event .

**To Reproduce**

The app should not crash

**Logs**

2019-03-30 15:58:47.648 8742-8742/com.eventyay.attendee E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 8742
    java.lang.IllegalStateException: View androidx.swiperefreshlayout.widget.SwipeRefreshLayout{136de54 V.ED..... ......ID 0,0-1080,1771 #7f09023d app:id/swiperefresh} does not have a NavController set
        at androidx.navigation.Navigation.findNavController(Navigation.java:84)
        at org.fossasia.openevent.general.event.EventsFragment$onViewCreated$eventClickListener$1.onClick(EventsFragment.kt:180)
        at org.fossasia.openevent.general.event.EventViewHolder$bind$2.onClick(EventViewHolder.kt:71)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:782)
        at android.view.View$PerformClick.run(View.java:25945)
        at android.os.Handler.handleCallback(Handler.java:874)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Screenshots**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22665789/55275050-396f1080-5306-11e9-8810-079e34dfee81.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nokia 6.1 Plus|
|Android Version| Pie 9.0 |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by aman210697** [comment]
How can I run it with live data, not a dummy?

**Comment by addiegupta** [comment]
change line 42 with line 38 in app:build.gradle i.e. change server to release

> How can I run it with live data, not a dummy?
