### ISSUE TITLE
App crashes when device connected to network but internet is not working in DayScheduleFragment

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-android#1479]
**Actual Behaviour**

App crashes when device connected to Mobile Data but internet is not working in DayScheduleFragment because of  NullPointerException.

**Expected Behaviour**

App shouldn't crash.

**LogCat for the issue**

`java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
                                                                            at android.support.design.widget.Snackbar.make(Snackbar.java:165)
                                                                            at org.fossasia.openevent.utils.ShowNotificationSnackBar.showSnackBar(ShowNotificationSnackBar.java:41)
                                                                            at org.fossasia.openevent.utils.ShowNotificationSnackBar.<init>(ShowNotificationSnackBar.java:35)
                                                                            at org.fossasia.openevent.fragments.DayScheduleFragment$6$1.<init>(DayScheduleFragment.java:328)
                                                                            at org.fossasia.openevent.fragments.DayScheduleFragment$6.inactiveConnection(DayScheduleFragment.java:328)
                                                                            at org.fossasia.openevent.utils.NetworkUtils$4$1.accept(NetworkUtils.java:158)
                                                                            at org.fossasia.openevent.utils.NetworkUtils$4$1.accept(NetworkUtils.java:152)`

**Steps to reproduce**

- Run app & turn off wifi connect to network which has no internet
- Go to schedule fragment
- Refresh schedule using swipe refresh layout

**Would you like to work on the issue?**

Yes

**Comment by mananwason** [comment]
Sorry but I'm not able to reproduce the issue. Please add clear steps always.

**Comment by Shailesh351** [comment]
I am also not manually able to produce this issue but i have faced this  approx 10 times. It will be good to null check
