### ISSUE TITLE
App crashes on search

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#1482]
**Logs**
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 23089
    java.lang.ClassCastException: androidx.appcompat.widget.SearchView$SavedState cannot be cast to android.widget.SearchView$SavedState
        at android.widget.SearchView.onRestoreInstanceState(SearchView.java:1441)
        at android.view.View.dispatchRestoreInstanceState(View.java:15780)
```

**Smartphone Info:**

|               | |
|---------------|-|
|Android Version|Nougat 7.1.1|

**Would you like to work on the issue?**

yes

**Comment by angmas1** [comment]
I'm already working on this if you don't mind, can I take this up?

**Comment by liveHarshit** [comment]
Resolved
