### ISSUE TITLE
App Crash on Network State Change

### ISSUE THREAD

**Issue by Ronak-59** [fossasia/open-event-android#1504]
**Actual Behaviour**

I was on Wifi and suddenly my brother switched off wifi router switch which resulted in change of State of Network in my device from Wifi to Data Connection - 4G

Now the App suddenly **crashed** and force stopped.

**Expected Behaviour**

Well, the app is supposed to remain stable on network change when the downloading of data is incomplete.

**Steps to reproduce it**

Try to switch from wifi to data connection when the app is open.

**LogCat for the issue**

05-07 10:50:32.398 10929-10929/org.fossasia.openevent E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: org.fossasia.openevent, PID: 10929
                                                                        io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'java.lang.String android.net.NetworkInfo.getTypeName()' on a null object reference
                                                                            at io.reactivex.internal.functions.Functions$14.accept(Functions.java:229)
                                                                            at io.reactivex.internal.functions.Functions$14.accept(Functions.java:226)
                                                                            at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:44)
                                                                            at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
                                                                            at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6176)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
                                                                         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.NetworkInfo.getTypeName()' on a null object reference
                                                                            at org.fossasia.openevent.utils.NetworkUtils.haveWifiConnection(NetworkUtils.java:58)
                                                                            at org.fossasia.openevent.utils.NetworkUtils.haveNetworkConnection(NetworkUtils.java:33)
                                                                            at org.fossasia.openevent.utils.NetworkUtils$1.call(NetworkUtils.java:40)
                                                                            at org.fossasia.openevent.utils.NetworkUtils$1.call(NetworkUtils.java:37)
                                                                            at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:35)
                                                                            at io.reactivex.Single.subscribe(Single.java:2693)
                                                                            at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
                                                                            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                            at java.lang.Thread.run(Thread.java:761)

**Screenshots of the issue**

**Would you like to work on the issue?**

No as I am implementing Chat feature between event organizer and users

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Comment by iamareebjamal** [comment]
I can work on it. It's a simple null check

**Comment by arp95** [comment]
yeah facing this issue.

**Comment by iamareebjamal** [comment]
I have fixed the code but could not reproduce the error.

Could any one of you please test the PR and see if error still persists

**Comment by Ronak-59** [comment]
Alright! Thanks for fixing the code.. Will try to reproduce the error while testing the PR and check if the error still exists or not.

**Comment by mananwason** [comment]
I wasn't able to reproduce the error either.
