### ISSUE TITLE
App crash on signup

### ISSUE THREAD

**Issue by addiegupta** [fossasia/open-event-android#1531]
**Describe the bug**

The app is crashing on clicking sign up after filling all fields correctly

**To Reproduce**

App crashes

**Expected behavior**

App should not crash

**Logs**

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 4377
    a.a.c.f: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | kotlin.UninitializedPropertyAccessException: lateinit property credentialsClient has not been initialized
        at a.a.f.a.a(RxJavaPlugins.java:367)
        at a.a.e.d.b.a_(ConsumerSingleObserver.java:65)
        at a.a.e.e.e.b$a.a_(SingleDoFinally.java:73)
        at a.a.e.e.e.c$a.a_(SingleDoOnSubscribe.java:77)
        at a.a.e.e.e.h$a.run(SingleObserveOn.java:81)
        at a.a.a.b.b$b.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:874)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property credentialsClient has not been initialized
        at org.fossasia.openevent.general.search.SmartAuthViewModel.saveCredential(SmartAuthViewModel.kt:76)
        at org.fossasia.openevent.general.auth.SignUpFragment$onCreateView$7.onChanged(SignUpFragment.kt:169)
        at org.fossasia.openevent.general.auth.SignUpFragment$onCreateView$7.onChanged(SignUpFragment.kt:46)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.r.setValue(MutableLiveData.java:50)
        at org.fossasia.openevent.general.utils.extensions.LiveDataExtensionsKt$nonNull$1.onChanged(LiveDataExtensions.kt:12)
        at androidx.lifecycle.p$a.onChanged(MediatorLiveData.java:152)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.r.setValue(MutableLiveData.java:50)
        at org.fossasia.openevent.general.common.SingleLiveEvent.setValue(SingleLiveEvent.kt:60)
        at org.fossasia.openevent.general.auth.SignUpViewModel$login$3.accept(SignUpViewModel.kt:78)
        at org.fossasia.openevent.general.auth.SignUpViewModel$login$3.accept(SignUpViewModel.kt:15)

**Screenshots**

![newcrashissue](https://user-images.githubusercontent.com/22665789/55562894-842bc680-5712-11e9-8094-a2c488e80019.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nokia 6.1 Plus|
|Android Version|Pie 9.0   |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by addiegupta** [comment]
Its strange Im unable to reproduce this now. Anyone else able to reproduce this?

**Comment by iamareebjamal** [comment]
Where's `credentialsClient` present?

**Comment by addiegupta** [comment]
> Where's `credentialsClient` present?

In app\src\playStore\java\org\fossasia\openevent\general\search\SmartAuthViewModel.kt

**Comment by addiegupta** [comment]
unfortunately this error is taking place only on the playstore release version

**Comment by iamareebjamal** [comment]
I know. There should not be lateinit property in ViewModels, change it please
