### ISSUE TITLE
App Crashes on Launch

### ISSUE THREAD

**Issue by abs51295** [fossasia/open-event-android#1626]
**Actual Behaviour**

Application is crashing on launching it after a fresh install.

**Expected Behaviour**

Application should not crash.

**Steps to reproduce it**

1) Uninstall and then install the app.
2) Launch the app.

**LogCat for the issue**

`05-31 23:24:15.572 18765-18883/org.fossasia.openevent E/SQLiteLog: (1) no such column: description
05-31 23:24:15.600 18765-18765/org.fossasia.openevent E/SQLiteLog: (1) no such column: color
05-31 23:24:15.606 18765-18765/org.fossasia.openevent E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: org.fossasia.openevent, PID: 18765
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{org.fossasia.openevent/org.fossasia.openevent.activities.MainActivity}: android.database.sqlite.SQLiteException: no such column: color (code 1): , while compiling: SELECT id, name, description, image, color FROM tracks ORDER BY name ASC
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                         Caused by: android.database.sqlite.SQLiteException: no such column: color (code 1): , while compiling: SELECT id, name, description, image, color FROM tracks ORDER BY name ASC
                                                                            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                                            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                                            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                            at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                            at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                            at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
                                                                            at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1165)
                                                                            at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1036)
                                                                            at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1204)
                                                                            at org.fossasia.openevent.dbutils.DatabaseOperations.getTrackList(DatabaseOperations.java:283)
                                                                            at org.fossasia.openevent.dbutils.DbSingleton.getTrackList(DbSingleton.java:140)
                                                                            at org.fossasia.openevent.fragments.TracksFragment.handleVisibility(TracksFragment.java:109)
                                                                            at org.fossasia.openevent.fragments.TracksFragment.onCreateView(TracksFragment.java:75)
                                                                            at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                            at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                            at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                            at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                            at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                            at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                            at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1270)
                                                                            at android.app.Activity.performStart(Activity.java:6689)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2622)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:154) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
`

**Would you like to work on the issue?**

No.

**Comment by rohanagarwal94** [comment]
@iamareebjamal please look into it ASAP. Nothing from my end as of yet.

**Comment by iamareebjamal** [comment]
Means you can't reproduce the error?

**Comment by rohanagarwal94** [comment]
yup

**Comment by iamareebjamal** [comment]
Taking a look. I think this is a database migration issue. New install should not give an error. Only clearing the data and launching new app on top of old one will.

**Comment by iamareebjamal** [comment]
Not crashing. This kind of error comes when you **don't** reinstall and just update the app from old version to new version. Database schema changes and can't find updated field. As we have no migrations set up it crashes. Can't happen on fresh installs though

**Comment by the-dagger** [comment]
This is a db migration issue, happens if you install a new version from an older one which had a different db schema @abs51295 .

@iamareebjamal @rohanagarwal94 Please ensure that this shouldn't happen, we often tend to ignore updating the db version.
