### ISSUE TITLE
Add downloading invoice for ticket ordered

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1700]
**Describe the feature you'd like**
Add downloading invoice for ticket ordered

**Would you like to work on the issue?**
Yes

**Comment by theLimitBreaker** [comment]
@anhanh11001  How is it different from Download tickets option ? Could you please explain?

**Comment by aggarwalpulkit596** [comment]
Duplicate #1338

**Comment by anhanh11001** [comment]
I'm just checking from open-event-frontend. There are 2 options - invoice and ticket
<img src="https://i.ibb.co/sCbBsKq/invoice.png" alt="invoice" width="300">   <img src="https://i.ibb.co/3h7Yd92/ticket.png" alt="ticket" width="300">

**Comment by anhanh11001** [comment]
I'm having 500 INTERNAL SERVER ERROR while fetching event invoice. Here are the logs. I'm not familiar with this error but is it from the server or are there any chances where the error is made by me
```
D/OkHttp: <-- 500 INTERNAL SERVER ERROR https://api.eventyay.com/v1/users/7622/event-invoices (228ms)
D/OkHttp: Server: nginx/1.14.0 (Ubuntu)
    Date: Sat, 04 May 2019 19:39:14 GMT
D/OkHttp: <-- 500 INTERNAL SERVER ERROR https://api.eventyay.com/v1/events/772/event-invoices (230ms)
D/OkHttp: Content-Type: application/vnd.api+json
D/OkHttp: Server: nginx/1.14.0 (Ubuntu)
D/OkHttp: Content-Length: 140
D/OkHttp: Connection: keep-alive
    Access-Control-Allow-Origin: *
    X-Sentry-ID: 0a12915859364caca8bb7aac644943af
D/OkHttp: Date: Sat, 04 May 2019 19:39:14 GMT
    Content-Type: application/vnd.api+json
    Content-Length: 140
    Connection: keep-alive
    Access-Control-Allow-Origin: *
D/OkHttp: X-Sentry-ID: 9c9a0a3d8dec47d6bac1c7737b88ba12
D/OkHttp: {"errors": [{"detail": "Unknown error", "source": {"pointer": ""}, "status": 500, "title": "Unknown error"}], "jsonapi": {"version": "1.0"}}
D/OkHttp: <-- END HTTP (140-byte body)
D/OkHttp: {"errors": [{"detail": "Unknown error", "source": {"pointer": ""}, "status": 500, "title": "Unknown error"}], "jsonapi": {"version": "1.0"}}
    <-- END HTTP (140-byte body)
D/InvoiceViewModel$loadInvoices: DEBUGGING fetching fail
D/InvoiceViewModel$loadInvoices: Error fetching invoices
    retrofit2.adapter.rxjava2.HttpException: HTTP 500 INTERNAL SERVER ERROR
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
```
Besides, the documentation is not clear as well. In here, the title is ` event invoice list of an user` but the description is `Get a single event invoice.`. Same goes for `event invoice list of an event` and `Get a single event invoice`
<img src="https://i.ibb.co/jH41sY1/Capture.png" alt="Capture" border="0">

@iamareebjamal please give your thoughts?

**Comment by iamareebjamal** [comment]
Raise an issue on server
