### ISSUE TITLE
App crash on navigating to different fragments 

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1715]
**Describe the bug**
It seems like there are mistakes in the latest commit that cause app crash on navigating to similar event fragment (Could possibly some other fragment as well)

**Logs**
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 16625
    java.lang.IllegalArgumentException: navigation destination com.eventyay.attendee:id/action_similar_events_to_event_details is unknown to this NavController
        at androidx.navigation.NavController.navigate(NavController.java:816)
        at androidx.navigation.NavController.navigate(NavController.java:757)
        at androidx.navigation.NavController.navigate(NavController.java:743)
        at androidx.navigation.NavController.navigate(NavController.java:875)
        at org.fossasia.openevent.general.event.topic.SimilarEventsFragment$onViewCreated$eventClickListener$1.onClick(SimilarEventsFragment.kt:98)
        at org.fossasia.openevent.general.event.EventViewHolder$bind$5.onClick(EventViewHolder.kt:94)
        at android.view.View.performClick(View.java:6291)
        at android.view.View$PerformClick.run(View.java:24931)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
I/Process: Sending signal. PID: 16625 SIG: 9
Application terminated.
```
**Would you like to work on the issue?**
Yes

**Comment by aggarwalpulkit596** [comment]
@anhanh11001 I might I've missed this one I checked each of them thoroughly

**Comment by anhanh11001** [comment]
@aggarwalpulkit596 yes I have checked them all, it seems like you only missed that one, rest is good
