### ISSUE TITLE
Unable to create orders for tickets which are free

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-android#1728]
**Describe the bug**
On trying to create new orders, first the message is displayed "Attendees created successfully" and then it displays "Unable to create order".

After this, the logs show that the created attendee is deleted.

Seems that the issue is with the order amount becoming null when the amount is 0.

**Logs**
```
com.eventyay.attendee D/OkHttp: {"errors": [{"detail": "Field may not be null.", "source": {"pointer": "/data/attributes/amount"}, "status": "422", "title": "Validation error"}], "jsonapi": {"version": "1.0"}}
2019-05-08 12:42:11.499 23901-24241/com.eventyay.attendee D/OkHttp: <-- END HTTP (177-byte body)
2019-05-08 12:42:11.516 23901-23901/com.eventyay.attendee D/AttendeeViewModel$createOrder: Failed creating Order
    retrofit2.adapter.rxjava2.HttpException: HTTP 422 UNPROCESSABLE ENTITY
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
```

**Would you like to work on the issue?**
- [ ] Yes
- [x] No

- Other: Not sure whether it is an issue with the app or on the server.

**Comment by ShridharGoel** [comment]
@liveHarshit @anhanh11001 Please have a look.

**Comment by uds5501** [comment]
@ShridharGoel The amount field requires something. Please make sure that a free ticket is pushing a `{amount : 0}` in data

**Comment by ShridharGoel** [comment]
@uds5501 An order with a combination of paid and unpaid tickets is working fine.

**Comment by uds5501** [comment]
@ShridharGoel Good, this means you just have to pass `{amount : 0}` in the post request of a free order, that should do

**Comment by iamareebjamal** [comment]
This is an issue on server and should be fixed. null should default to 0

**Comment by anhanh11001** [comment]
@ShridharGoel this issue is fixed, can you close it?
