### ISSUE TITLE
App crashes on clicking SimilarEvent in OrderCompletedFragment

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-android#1895]
**Describe the bug**
App crashes on clicking SimilarEvent in OrderCompletedFragment

**Logs**
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 17305
    java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Collection.contains(java.lang.Object)' on a null object reference
        at androidx.collection.MapCollections.retainAllHelper(MapCollections.java:481)
        at androidx.collection.ArrayMap.retainAll(ArrayMap.java:164)
        at androidx.fragment.app.FragmentTransition.captureOutSharedElements(FragmentTransition.java:803)
        at androidx.fragment.app.FragmentTransition.configureSharedElementsReordered(FragmentTransition.java:575)
        at androidx.fragment.app.FragmentTransition.configureTransitionsReordered(FragmentTransition.java:235)
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:135)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1817)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```
**Screenshots**
<img src="https://i.ibb.co/yypvJDv/ezgif-2-6a2046d3f6cc.gif" alt="ezgif-2-6a2046d3f6cc" border="0">

**Would you like to work on the issue?**
Yes

**Comment by liveHarshit** [comment]
Not crashing on my device. You android version?

**Comment by anhanh11001** [comment]
8.0.0, API 26

**Comment by liveHarshit** [comment]
> 8.0.0, API 26

Also crashing on API Q

**Comment by anhanh11001** [comment]
@liveHarshit I'm just curious, what's the meaning of milestone in here?

**Comment by liveHarshit** [comment]
> @liveHarshit I'm just curious, what's the meaning of milestone in here?

Mean, the issue should solve before release v0.4.0.
