### ISSUE TITLE
App crashes when share tracks fab pressed 

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-android#428]
This is the stacktrace. This happens when we open a bookmarked tracked and then go back to the tracks list and share the tracks list.
```
06-22 01:53:47.634 25980-25980/org.fossasia.openevent E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: org.fossasia.openevent, PID: 25980
                                                                        java.lang.RuntimeException: Unable to instantiate service org.fossasia.openevent.Services.BookmarkAlarmService: java.lang.InstantiationException: java.lang.Class<org.fossasia.openevent.Services.BookmarkAlarmService> has no zero argument constructor
                                                                            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2862)
                                                                            at android.app.ActivityThread.-wrap4(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                         Caused by: java.lang.InstantiationException: java.lang.Class<org.fossasia.openevent.Services.BookmarkAlarmService> has no zero argument constructor
                                                                            at java.lang.Class.newInstance(Native Method)
                                                                            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2859)
                                                                            at android.app.ActivityThread.-wrap4(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by the-dagger** [comment]
@mananwason have you started working on this?
I would love to give this a shot if that's ok.

**Comment by mananwason** [comment]
@the-dagger Go ahead. I'll take up something else.

**Comment by mananwason** [comment]
@the-dagger Are you working on this. Please fix this asap as it is a major bug. Adding the urgent label

**Comment by the-dagger** [comment]
Yep will fix it today itself.
Was unable to do so due to time constraints.

On Sunday, June 26, 2016, Manan Wason <notifications@github.com> wrote:

> @the-dagger <https://github.com/the-dagger> Are you working on this.
> Please fix this asap as it is a major bug. Adding the urgent label
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/open-event-android/issues/428#issuecomment-228584504>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGQtliyT46f99dtN8e-kD4LPfp7tB2ckks5qPgfkgaJpZM4I7JZY>
> .
>


-- 
Thanks,
Harshit Dwivedi
Contact : +919968195588
GitHub <https://github.com/the-dagger> | LinkedIn
<https://in.linkedin.com/in/hadwivedi>
Google Play <https://goo.gl/wl3loD> | Facebook
<https://www.facebook.com/daggerdwivedi>

**Comment by mananwason** [comment]
Okay great 👍
