### ISSUE TITLE
Clicking on a track from locations causes force close.

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-android#561]
@mananwason I believe this issue is related to the parser as well.
```
Process: org.fossasia.openevent, PID: 3531
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.fossasia.openevent.data.Track.getId()' on a null object reference
at org.fossasia.openevent.activities.LocationActivity$1.onItemClick(LocationActivity.java:78)
at org.fossasia.openevent.utils.ViewHolder$Viewholder$1.onClick(ViewHolder.java:40)
at android.view.View.performClick(View.java:5198)
at android.view.View$PerformClick.run(View.java:21147)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by the-dagger** [comment]
Fixed in #556
