### ISSUE TITLE
[Fdroid]App crashing on schedules.

### ISSUE THREAD

**Issue by gogeta95** [fossasia/open-event-android#638]
App is crashing on schedules @mananwason @the-dagger.
steps to reproduce crash:

>1. open schedule.
>2. turn internet OFF.
>3. turn internet ON.

adding stacktrace: 
```
08-23 22:54:29.889 2571-2571/org.fossasia.openevent E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.fossasia.openevent, PID: 2571
                                                                      java.lang.RuntimeException: Could not dispatch event: class org.fossasia.openevent.events.CounterEvent to handler [EventHandler public void org.fossasia.openevent.activities.MainActivity.onCounterReceiver(org.fossasia.openevent.events.CounterEvent)]: Invalid index 0, size is 0
                                                                          at com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
                                                                          at com.squareup.otto.Bus.dispatch(Bus.java:387)
                                                                          at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
                                                                          at com.squareup.otto.Bus.post(Bus.java:337)
                                                                          at org.fossasia.openevent.OpenEventApp$1.run(OpenEventApp.java:59)
                                                                          at android.os.Handler.handleCallback(Handler.java:733)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                          at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                          at java.util.ArrayList.get(ArrayList.java:308)
                                                                          at org.fossasia.openevent.utils.ISO8601Date.setEventTimezone(ISO8601Date.java:135)
                                                                          at org.fossasia.openevent.utils.ISO8601Date.getDateObject(ISO8601Date.java:91)
                                                                          at org.fossasia.openevent.activities.MainActivity.syncComplete(MainActivity.java:327)
                                                                          at org.fossasia.openevent.activities.MainActivity.onCounterReceiver(MainActivity.java:511)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
                                                                          at com.squareup.otto.Bus.dispatch(Bus.java:385)
                                                                          at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368) 
                                                                          at com.squareup.otto.Bus.post(Bus.java:337) 
                                                                          at org.fossasia.openevent.OpenEventApp$1.run(OpenEventApp.java:59) 
                                                                          at android.os.Handler.handleCallback(Handler.java:733) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                          at dalvik.system.NativeStart.main(Native Method)
```

Android version: 4.4.4, API 19
Device: Genymotion emulator , 768x1280

**Comment by gogeta95** [comment]
found the cause, its because Geocoder backend service (may be a part of google play services?) is missing in genymotion. quoting from the [Geocoder docs](https://developer.android.com/reference/android/location/Geocoder.html):

>Reverse geocoding is the process of transforming a (latitude, longitude) coordinate into a (partial) address. The amount of detail in a reverse geocoded location description may vary, for example one might contain the full street address of the closest building, while another might contain only a city name and postal code. **The Geocoder class requires a backend service that is not included in the core android framework. The Geocoder query methods will return an empty list if there no backend service in the platform. Use the isPresent() method to determine whether a Geocoder implementation exists.**

**Comment by mananwason** [comment]
So we can close this then @gogeta95.

**Comment by the-dagger** [comment]
@mananwason this issue is in FDroid variant only, so probably some issue with our implementation.
Let's dig this a bit deeper once we are done with remaining issues.

**Comment by mananwason** [comment]
Oh got it @the-dagger. Actually I have used geocoder in https://github.com/fossasia/open-event-android/blob/a075beb61d4a65e06ca075344741973cda69df42/android/app/src/main/java/org/fossasia/openevent/utils/ISO8601Date.java.

This is used to get conference timezone by the coordinates of the event. I did this to make the app customisable. Will find a fix for this.

**Comment by the-dagger** [comment]
Cool :+1:
