### ISSUE TITLE
APP CRASH : Edit Profile is crashing the app

### ISSUE THREAD

**Issue by trancenoid** [fossasia/open-event-android#683]
After logging in and navigating to the profile section, clicking on Edit Profile from the menu bar, the app crashes.
EDIT : Only happens with profiles with no profile picture. A user having a profile picture will face no issue

**To Reproduce**
1. Login / Sign Up 
2. Navigate to Profile Tab
3. Open Menu Bar (3 Dots)
4. Choose Edit Profile

**Expected behavior**
Edit Profile fragment must open up normally

**Logs**
LOGCAT -
`2018-11-03 19:39:58.330 17737-17737/com.eventyay.attendee E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 17737
    java.lang.IllegalArgumentException: Path must not be empty.
        at com.squareup.picasso.Picasso.load(Picasso.java:332)
        at org.fossasia.openevent.general.auth.EditProfileFragment$onCreateView$1.onChanged(EditProfileFragment.kt:62)
        at org.fossasia.openevent.general.auth.EditProfileFragment$onCreateView$1.onChanged(EditProfileFragment.kt:33)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at org.fossasia.openevent.general.auth.ProfileFragmentViewModel$fetchProfile$3.accept(ProfileFragmentViewModel.kt:41)
        at org.fossasia.openevent.general.auth.ProfileFragmentViewModel$fetchProfile$3.accept(ProfileFragmentViewModel.kt:10)
        at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
        at io.reactivex.internal.operators.single.SingleDoFinally$DoFinallyObserver.onSuccess(SingleDoFinally.java:73)
        at io.reactivex.internal.operators.single.SingleDoOnSubscribe$DoOnSubscribeSingleObserver.onSuccess(SingleDoOnSubscribe.java:77)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)`

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device        | Moto G4 |
|Android Version| Nougat 7.0 |

**Would you like to work on the issue?**

 Yes

**Comment by codepoet2017390** [comment]
Just tried reproducing the issue on a OnePlus 5 Android Oreo 8.1. This issue does not persist there.

**Comment by iamareebjamal** [comment]
This depends on which profile you are trying to view
