### ISSUE TITLE
Add Goto Search button in empty Likes tab

### ISSUE THREAD

**Issue by trancenoid** [fossasia/open-event-android#690]
**Describe the feature you'd like**
Add a **Goto Events** Button in the Likes tab when its empty.

**Additional context**
The **Likes** tab simply have a message saying "Find something to do", which can be represented better by a button that takes the user to events tab. 

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other: Suggestions are welcome

**Comment by ShridharGoel** [comment]
@trancenoid Are you still working on it?

**Comment by trancenoid** [comment]
@iamareebjamal Can you please review my commit

**Comment by iamareebjamal** [comment]
Send a PR

**Comment by trancenoid** [comment]
@iamareebjamal I found a problem in my current implementation, on clicking the "Go Explore" button, the search fragment is opened but the support action bar still show "Likes" as the currently selected tab. I have tried using the following code in FavouriteFragment but it doesn't work
```
val mMenuItem : MenuItem = navigation.menu.findItem(R.id.navigation_search)
mMenuItem.setChecked(true)
```
here is the stack trace : 
```
2018-12-21 14:39:43.071 29915-29915/com.eventyay.attendee E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 29915
    java.lang.IllegalStateException: navigation must not be null
        at org.fossasia.openevent.general.favorite.FavoriteFragment$onCreateView$1.onClick(FavoriteFragment.kt:62)
        at android.view.View.performClick(View.java:5612)
        at android.view.View$PerformClick.run(View.java:22285)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by shiv07tiwari** [comment]
@trancenoid Can i take up this issue ?

**Comment by trancenoid** [comment]
@shiv07tiwari Sure
