### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by passiondroid** [fossasia/open-event-android#715]
Found a crash. 
Steps which i performed - 
1. Launched the app
2. Selected a track
3. Opened a session detail
4. Bookmark the session
5. Press back twice to reach the first activity
6. Now do swipe refresh. As soon as the refresh gets finished, app crashes.

Many times app did not crashed by performing the above steps. So there may be few other things which is causing the crash. Below is the crash log - 

> 09-26 18:07:00.236 19148-19148/org.fossasia.openevent E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                         Process: org.fossasia.openevent, PID: 19148
>                                                                         java.lang.RuntimeException: Could not dispatch event: class org.fossasia.openevent.events.TracksDownloadEvent to handler [EventHandler public void org.fossasia.openevent.fragments.TracksFragment.onTrackDownloadDone(org.fossasia.openevent.events.TracksDownloadEvent)]: Attempt to invoke virtual method 'void android.support.v4.widget.SwipeRefreshLayout.setRefreshing(boolean)' on a null object reference
>                                                                             at com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
>                                                                             at com.squareup.otto.Bus.dispatch(Bus.java:387)
>                                                                             at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
>                                                                             at com.squareup.otto.Bus.post(Bus.java:337)
>                                                                             at org.fossasia.openevent.OpenEventApp$1.run(OpenEventApp.java:58)
>                                                                             at android.os.Handler.handleCallback(Handler.java:746)
>                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                             at android.os.Looper.loop(Looper.java:148)
>                                                                             at android.app.ActivityThread.main(ActivityThread.java:5443)
>                                                                             at java.lang.reflect.Method.invoke(Native Method)
>                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
>                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
>                                                                          Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.SwipeRefreshLayout.setRefreshing(boolean)' on a null object reference
>                                                                             at org.fossasia.openevent.fragments.TracksFragment.onTrackDownloadDone(TracksFragment.java:183)
>                                                                             at java.lang.reflect.Method.invoke(Native Method)
>                                                                             at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
>                                                                             at com.squareup.otto.Bus.dispatch(Bus.java:385)
>                                                                             at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368) 
>                                                                             at com.squareup.otto.Bus.post(Bus.java:337) 
>                                                                             at org.fossasia.openevent.OpenEventApp$1.run(OpenEventApp.java:58) 
>                                                                             at android.os.Handler.handleCallback(Handler.java:746) 
>                                                                             at android.os.Handler.dispatchMessage(Handler.java:95) 
>                                                                             at android.os.Looper.loop(Looper.java:148) 
>                                                                             at android.app.ActivityThread.main(ActivityThread.java:5443) 
>                                                                             at java.lang.reflect.Method.invoke(Native Method) 
>                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
>                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 

Will try to fix it.

**Comment by amitiwary999** [comment]
App crash even if session is not bookmarked.

**Comment by amitiwary999** [comment]
@passiondroid are you working on this?
@the-dagger I would like to work on this.

**Comment by passiondroid** [comment]
@amitiwary999 You can continue to fix it.

**Comment by amitiwary999** [comment]
@jig08 I think there is a problem with circleci. My previous pr #732 is pending.can you review it so that I can start work on this issue.

**Comment by amitiwary999** [comment]
@dhluong90 Sir are you taking about issue #720 or this issue(i.e #715)?

**Comment by dhluong90** [comment]
Look #720 and #715 are the same.

**Comment by dhluong90** [comment]
App crash when we revisit any page: 
track, speaker, sponsors, location. you can try it.

**Comment by amitiwary999** [comment]
Yeah tried it.

**Comment by amitiwary999** [comment]
So are you sending a new  PR or I open a new PR?

**Comment by dhluong90** [comment]
I sent it. Please help me review it. Thank @amitiwary999 
https://github.com/fossasia/open-event-android/pull/733

**Comment by amitiwary999** [comment]
@dhluong90 please inform before sending PR.

**Comment by amitiwary999** [comment]
@the-dagger this issue is solved so close this issue.
