### ISSUE TITLE
App Crashing on bookmarking any session

### ISSUE THREAD

**Issue by batraabhishek** [fossasia/open-event-android#84]
When I am trying to bookmark any session app crashes. Though on running the app again I can see it as bookmarked. 

There might be some issue with the code running after database transaction. 

Removing bookmark works good though.

**Comment by mananwason** [comment]
Seeing the logs, there is something wrong with the BookmarkAlarmService constructor. Let me figure it out and fix it.

**Comment by opticod** [comment]
with the changes made,I ran it in emulator (Nexus 5 API 23),It ran perfectly and build was also successful.

But after committing the change and making a PR,its showing this message

"continuous-integration/travis-ci/pr — The Travis CI build failed"

Do I missing something ?

Thank You

**Comment by mananwason** [comment]
This means that the travis build is failing. See the logs and figure out what is the error.

**Comment by opticod** [comment]
![screenshot from 2015-12-06 01-30-27](https://cloud.githubusercontent.com/assets/13851773/11609907/2c3275ae-9bb9-11e5-9b9c-bbce7e2fa153.png)


![screenshot from 2015-12-06 01-34-52]
(https://cloud.githubusercontent.com/assets/13851773/11609922/a5c001a2-9bb9-11e5-9ea8-835d3624afc5.png)

To me it seems like a bug of travis.Will you please rebuild it? From my account in my first build It showed error but in 2nd build it has passed .

**Comment by creativepsyco** [comment]
yep, it is a adb+travis inconsistency that keeps happening with multiple flavor builds, don't know why, probably should change the testing script to do a flavor testing, one by one.

**Comment by mananwason** [comment]
@creativepsyco the main branch is also failing the travis build due to InstallException. We should fix this.

**Comment by creativepsyco** [comment]
ok i am looking into.

**Comment by mRokita** [comment]
```java
12-07 21:50:49.792  31977-31977/org.fossasia.openevent E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.fossasia.openevent, PID: 31977
    java.lang.NumberFormatException: Invalid int: "10 mins before"
            at java.lang.Integer.invalidInt(Integer.java:138)
            at java.lang.Integer.parse(Integer.java:410)
            at java.lang.Integer.parseInt(Integer.java:367)
            at java.lang.Integer.parseInt(Integer.java:334)
            at org.fossasia.openevent.activities.SessionDetailActivity.createNotification(SessionDetailActivity.java:134)
            at org.fossasia.openevent.activities.SessionDetailActivity.onOptionsItemSelected(SessionDetailActivity.java:106)
            at android.app.Activity.onMenuItemSelected(Activity.java:2908)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:353)
            at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:144)
            at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
            at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
            at android.support.v7.internal.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:74)
            at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:164)
            at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:740)
            at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
            at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
            at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:598)
            at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
            at android.view.View.performClick(View.java:5198)
            at android.view.View$PerformClick.run(View.java:21147)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
It still crashes. I would like to fix it as my GCI task :)

**Comment by mananwason** [comment]
can you provide an instance when it crashes?

**Comment by mRokita** [comment]
I would like to see it added as my GCI task :)

**Comment by mRokita** [comment]
NOTICE: after updating the app on a device which has already some non-default notification settings, it might crash until you won't change them (I've changed notification resource type from String to Int)
