### ISSUE TITLE
App crashes due to snackbar text

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-android#840]
**Describe the bug**
App crashes while opening another fragment during snack bar handler is running.

**To Reproduce**
1. Log out
2. Click on profile
3. Now instantly click on tickets within a second

**Logs**
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 2674
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
        at android.content.ComponentName.<init>(ComponentName.java:128)
        at android.content.Intent.<init>(Intent.java:4910)
        at org.fossasia.openevent.general.auth.ProfileFragment.redirectToLogin(ProfileFragment.kt:44)
```

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Mi Max 2|
|Android Version|Nougat 7.1|

**Would you like to work on the issue?**

Has PR #838

**Comment by liveHarshit** [comment]
> @liveHarshit snackbar handlers will be removed after #838

Cool. Mention this issue in the PR. So, It will close when PR got merged.
