### ISSUE TITLE
App crashes on repeated click on profile fragment if not logged in.

### ISSUE THREAD

**Issue by kshitijsuri90** [fossasia/open-event-android#863]
**Describe the bug**

App crashes on repeated pressing of profile button in bottom navigation bar if the user has not logged in.

**To Reproduce**

1. Log out if logged in.
2. Press Profile fragment button repeatedly(twice-thrice).

**Expected behavior**

App should not crash

**Logs**

2019-01-09 00:33:28.980 2749-2749/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 2749
    java.lang.IllegalStateException: View androidx.coordinatorlayout.widget.CoordinatorLayout{1d81d45 V.E...... ......ID 0,0-1080,1563 #7f080169 app:id/profileCoordinatorLayout} does not have a NavController set
        at androidx.navigation.Navigation.findNavController(Navigation.java:83)
        at org.fossasia.openevent.general.auth.ProfileFragment.redirectToLogin(ProfileFragment.kt:43)
        at org.fossasia.openevent.general.auth.ProfileFragment.access$redirectToLogin(ProfileFragment.kt:35)
        at org.fossasia.openevent.general.auth.ProfileFragment$onCreateView$1.run(ProfileFragment.kt:62)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-01-09 00:37:50.880 4114-4114/com.eventyay.attendee E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 4114
    java.lang.IllegalStateException: View androidx.coordinatorlayout.widget.CoordinatorLayout{9350763 V.E...... ......ID 0,0-1080,1563 #7f080169 app:id/profileCoordinatorLayout} does not have a NavController set
        at androidx.navigation.Navigation.findNavController(Navigation.java:83)
        at org.fossasia.openevent.general.auth.ProfileFragment.redirectToLogin(ProfileFragment.kt:43)
        at org.fossasia.openevent.general.auth.ProfileFragment.access$redirectToLogin(ProfileFragment.kt:35)
        at org.fossasia.openevent.general.auth.ProfileFragment$onCreateView$1.run(ProfileFragment.kt:62)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Screenshots**

![app_crash](https://user-images.githubusercontent.com/34534870/50852967-0b350100-13a7-11e9-94dc-31581e417678.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |One Plus 5|
|Android Version|Android Pie 9.0.0 |

**Additional context**

@iamareebjamal @nikit19  @liveHarshit @simarsingh24 Your views?

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by GOVINDDIXIT** [comment]
@kshitijsuri90 this issue will be fixed by #838

**Comment by liveHarshit** [comment]
Duplicate of #840

**Comment by kshitijsuri90** [comment]
Okay @GOVINDDIXIT

**Comment by kshitijsuri90** [comment]
Mention this issue too when you submit PR so it will get closed when PR is merged. @GOVINDDIXIT

**Comment by liveHarshit** [comment]
> Mention this issue too when you submit PR so it will get closed when PR is merged. @GOVINDDIXIT

This issue is duplicate
