### ISSUE TITLE
App crash on clicking Profile twice from NavigationView

### ISSUE THREAD

**Issue by addiegupta** [fossasia/open-event-android#887]
**Describe the bug**

On opening the app and pressing the Profile icon from BottomNavigationView ( in my case, I havent  signed in yet), pressing the profile icon again crashes the app.

**To Reproduce**

1. Launch app
2. Click on 'Profile' from BottomNavigationView
3. Click on 'Profile' a second time

**Expected behavior**

The app should not have crashed

**Logs**

2019-01-13 22:05:14.779 23366-23366/com.eventyay.attendee E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 23366
    java.lang.IllegalStateException: View androidx.coordinatorlayout.widget.CoordinatorLayout{fe651a V.E...... ......ID 0,0-1080,1771 #7f08016e app:id/profileCoordinatorLayout} does not have a NavController set
        at androidx.navigation.Navigation.findNavController(Navigation.java:83)
        at org.fossasia.openevent.general.auth.ProfileFragment.redirectToLogin(ProfileFragment.kt:45)
        at org.fossasia.openevent.general.auth.ProfileFragment.access$redirectToLogin(ProfileFragment.kt:37)
        at org.fossasia.openevent.general.auth.ProfileFragment$onCreateView$1.run(ProfileFragment.kt:64)
        at android.os.Handler.handleCallback(Handler.java:874)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Screenshots**

![issue 885](https://user-images.githubusercontent.com/22665789/51087987-66d50500-1780-11e9-826b-1a3deb40325c.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |HMD Nokia 6.1 Plus|
|Android Version| Pie 9.0 |

**Additional context**

If the issue does not get reproduced, try signing out from account.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by liveHarshit** [comment]
I think this issue is due to post handlers which are removed in PR #830 or PR #838.  Can you please check again with latest commits?

**Comment by addiegupta** [comment]
@liveHarshit I just checked, the issue seems to be fixed. However I think it is not due to #838 as at the time of creating this issue I was on the latest version.
